### ISSUE TITLE
Enhance the pbench-agent ansible playbook to open the firewall for the redis-server and Tool Data Sink

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1891]
We should consider enhancing the pbench-agent playbooks to open ports `17001` (hex for "one tool", used by the `redis-server`) and `8080` (used by the Tool Data Sink).

See also #1890.

**Comment by ndokos** [comment]
We have a role for that in `agent/ansible/pbench/agent/roles/pbench_firewall_open_ports`. The ports are 17001 (for redis) and 8080 (for the tool data sink) by default, but can be reconfigured by defining `pbench_redis_port` and/or `pbench_wsgi_port` in the inventory file.

There is a (trivial) example playbook available internally which just runs this role:

```
---
- name: open ports for redis and tool data sink
  hosts: controllers
  remote_user: root

  roles:
    - pbench_firewall_open_ports
```

Although all the roles we use (and upload to Ansible Galaxy) are in the tree, playbooks are a different story. I will open an issue to track what we do with them.
