### ISSUE TITLE
`pbench-move-results` NG and its support structures on the server side.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#797]
* History
@tenstormavi has implemented an inotify-based implementation of the server scripts which decreases latency and will allow us to containerize the server for easier deployment in a cloud environment. However, the mechanism required a backward-incompatible change to `pbench-move-results` and the proposed mechanism to deal with it (have `pbench-move-results` call a server-side script to do what's needed) was deemed a backward step. Although this change is actually part of the current release (and is an improvement over doing things explicitly in the client), it will not be used to resolve the backward incompatibility noted above. Instead, we'll work along the lines of the following proposal (but there will be comments, so please make sure to (re-)read the whole issue before implementing anything and update the issue with any questions and problems you encounter. 

* Proposal
Based on comments by @portante, we are planning to do the following:

- Use the versioning mechanism on the server side to deal with the incompatibiliy: old clients will remain unchanged and the data will be processed exactly as they are processed today (eventually, once most clients
have been updated, we'll declare a moratorium and turn it off but no date has been set); new clients will use the new mechanism described below.

- `pbench-move-results` will copy *one* tarball per result to the server (eventually, that will become a PUT into an object filesystem). The tarball will package up a few pieces that are currently copied separately: the compresed tarball of the results, its MD5 sum and the (optional) prefix file. In addition, the controller host name will be added as additional information (currently it's encoded as part of the pathname of the tarball).

- In addition to bumping the fs version, we'll need to provide new `results-host-info` settings.

- On the server side, the inotified server will watch the download directory and provide impedance matching to the current processing pipeline (which remains substantially unchanged).

- We'll change the archive directory structure to make it deeper and not as wide, by using the MD5 string of the tarball to implement a  (on-disk) trie (like git, or gluster): e.g. the MD5 sum 7341243af6d9af1025cbec71023dbff7 will generate a pathname of `73/41/7341243af6d9af1025cbec71023dbff7` to a directory that will hold the unpacked "container" tarball. [Question: does this structure limit us in any way? Is there anything that becomes harder? Need to think about this some more]

- The (inotified) server will create a symlink to the "inner" tarball in a TODO state directory and add an entry to the list of files to be processed. From that point on, the current processing pipeline will take over and perform the same tasks it does today.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [`pbench-move-results` NG and its support structures on the server side](https://trello.com/c/2igA5oks/41-pbench-move-results-ng-and-its-support-structures-on-the-server-side)

**Comment by k-rister** [comment]
Is there any way we can have a notification of some type sent when a result has completed processing?

**Comment by portante** [comment]
@k-rister, we can setup an ElastAlert to email or post in IRC, etc. when a new result shows up in Elasticsearch.

**Comment by k-rister** [comment]
Is that something we can do right now?  I pushed a result 2 hours ago and I'm just having to randomly hit refresh to see when it shows up...

**Comment by portante** [comment]
@k-rister, so I'll talk to you off-line about the specific deployment we have and how to work with it which is not germane to general pbench.

Regarding Elastalert, here is an example alert root for a disk error in logs.  We can create the query string and index name for finding results added in the same way:

```
name: "Disk Errors"
es_host: localhost
es_port: 9200
use_strftime_index: true
index: "logstash-%Y.%m.%d"
type: frequency
num_events: 1
timeframe:
    minutes: 5
filter:
- query:
    query_string:
      query: "rsyslog.programname:kernel AND ((message:\"buffer i/o error on device\" AND message:\"logical block\") OR (message:\"blk_update_request: I/O error dev\" AND message:sector) OR (message:XFS AND NOT (level:debug OR level:info OR level:notice OR level:warning)))"
alert:
- "email"
email:
- "alert@example.com"
```
